version: '3.1'
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - aopvol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'aop'
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis
    ports:
      - 6379:6379
volumes:
  aopvol:
