version: '3.1'
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - chatVol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'chatting'
      MYSQL_ROOT_PASSWORD: password
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
volumes:
  chatVol:
  data:
