version: '3.1'
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - calendarvol:/var/lib/mysql
      - './scripts:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_DATABASE: 'calendar'
      MYSQL_ROOT_PASSWORD: password
volumes:
  calendarvol:
