version: '3.1'
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysqlvol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'badminton'
      MYSQL_ROOT_PASSWORD: password

volumes:
  mysqlvol:
