version: '3.1'
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - productVol:/var/lib/mysql
      - './scripts:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_DATABASE: 'product'
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis
    ports:
      - 6379:6379
volumes:
  productVol:
